#-----------------------------Configuration for eccfinder You can MODIFY these parameters as you want :)-----------------------------------------
args:
 # this option it's for launch ont longreads analysis
 - "map-ont"
 # this option it's where you locate your fastqfiles

 -  "./data/M1.fastq"

 - "-r"

 # this option it's where you locate your fastafiles for reference genome
 - "./data/hetre.fa"

 # this option it's to add your gff file GENE(location) plant or human
 - "-gene"

 - "./data/forest.gff"

 # this option it's to locate your gff file  TE(location) human
 - "-te"

 - "/home/archimede/Documents/annotations/hg38_TE.sorted.gtf"
 # this option it's to locate your sorted gff file Alu(locaion) human
 - "-alu"

 - "/home/archimede/Documents/annotations/hg38_TE.sorted_AluONLY.gtf"

#----------------------Criteria Human(human) or Plants(plant)----------------------------------------------
 - "-org"
# put the name of the organism human or plant
 - "plant"
#--------------------------config for Tandem Repeat Criteria---------------------------------
 - "-n"
#-----minimum copy number of tandem repeat in a long read (>=2) [2]--------------------------
 - "2"
#--------------------------------------
 - "-e"
#------------------maximum allowed divergence rate between two consecutive repeats-----------
 - "0.25"
#--------------------------------------------------------------------------------------------
 - "-s"
#---minimum period size of tandem repeat (>=2) [30]---------------------
 - "30"
#-----------------------end config tandem repeat------------------------------------------

#---------------------------Config for region of peak probably circle---------------------
# - "-yv"
 - "-l"
#---Minimum length of a peak--------------------------------------------------------------
 - "200"
#-----------------------------------------------------------------------------------------
 - "-d"
#---Maximum distance between signif. sites (def. 100)-------------------------------------
 - "100"
#-----------------------------------------------------------------------------------------
 - "-p"
#--------Maximum p-value (def. 0.01)------------------------------------------------------
 - "0.05"

#-------------------end of Gene enrichment------------------------------------------------

#------------------------Config for filtering region--------------------------------------

 - "--min-read"
#----------------------filter locus by unique mapped read number-------------------------
 - "1"
#----------------------------------------------------------------------------------------

 - "--min-bound"
#------filter locus at regions by boundary coverage---------------------------------------
 - "0.1"
#-----------------------------------------------------------------------------------------
 - "--min-cov"
#---------------------minimum coverage of detected eccDNA loci----------------------------
 - "1"
#--------------------------end filtering locus regions------------------------------------
 - "-o"

# - "OUTPUT VALUE"
 - "M1"
#------------------------------END Configuration------------------------------------------


